### ISSUE TITLE
ตรวจสอบการบ้าน HTML ข้อ3

### ISSUE THREAD

**Issue by codecamp-official-thailand** [virachai/Homework_codecamp_8#3]
ทางทีมงานได้ทำการตรวจสอบการบ้านของคุณ virachai เรียบร้อยแล้ว
พบว่าไม่มีส่วนไหนต้องแก้ไขเพิ่มเติม ผ่านเรียบร้อยครับ :)

**Comment by virachai** [comment]
รับทราบครับ
